title: Hitchens-Obraz
description: >- # this means to ignore newlines until "baseurl:"
  Obraz port of Hitchens theme
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: ideally https://domain.com/folder, but would work with /folder, folder or ""
url: "https://hitchens-obraz.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
github_username:  sevelev-ens

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"


data:
  menu:
    - title: About
      url: /about.html

    - title: Source
      url: https://github.com/sevelev-ens/hitchens-obraz

    - title: Designer
      url: http://patdryburgh.com